In [1]:
import pandas as pd

In [2]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


In [3]:
df=pd.read_csv("Poem_classification - test_data.csv")


In [4]:
df

Genre                                               Poem
0          Music  A woman walks by the bench I’m sitting onwith ...
1          Music  Because I am a boy, the untouchability of beau...
2          Music  Because today we did not leave this world,We n...
3          Music  Big Bend has been here, been here. Shouldn’t i...
4          Music  I put shells there, along the lip of the road....
..           ...                                                ...
145  Environment  To pick a tulip from the garden, the red one. ...
146  Environment  We are as clouds that veil the midnight moon; ...
147  Environment  When pulled, the spider web took another form....
148  Environment  Whose woods these are I think I know. His hous...
149  Environment  you can make the maples blazejust by stopping ...

[150 rows x 2 columns]

In [5]:
vectorizer = TfidfVectorizer(stop_words = 'english', ngram_range = (1,3))


In [6]:
features = vectorizer.fit_transform(df['Poem'].values)

In [12]:
features

<150x8847 sparse matrix of type '<class 'numpy.float64'>'
	with 10015 stored elements in Compressed Sparse Row format>

In [7]:
Cos_Sim = cosine_similarity(features)


In [11]:
Cos_Sim

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [13]:
len(Cos_Sim)

150

In [15]:
Cos_Sim[0]

array([1.        , 0.        , 0.        , 0.        , 0.01730585,
       0.01047722, 0.00429205, 0.        , 0.        , 0.00378481,
       0.        , 0.        , 0.        , 0.        , 0.00494144,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.0185738 , 0.00462023, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.01055808, 0.        ,
       0.        , 0.01138182, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.00449492, 0.        ,
       0.00975451, 0.00872369, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.01392402, 0.        , 0.01174649, 0.        , 0.        ,
       0.00386017, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.00689044, 0.        , 0.     

In [14]:
type(Cos_Sim)

numpy.ndarray

In [8]:
print(df.loc[0,'Poem'])

A woman walks by the bench I’m sitting onwith her dog that looks part Lab, part Buick,stops and asks if I would like to dance.I smile, tell her of course I do. We decideon a waltz that she begins to hum.


In [9]:
Test = pd.DataFrame(list(enumerate(Cos_Sim[0])), columns = ['Poem_index','Similarity'])

In [16]:
Test

Poem_index  Similarity
0             0    1.000000
1             1    0.000000
2             2    0.000000
3             3    0.000000
4             4    0.017306
..          ...         ...
145         145    0.000000
146         146    0.003991
147         147    0.000000
148         148    0.000000
149         149    0.000000

[150 rows x 2 columns]

In [20]:
Test.sort_values(by="Similarity",ascending=False)

Poem_index  Similarity
0             0    1.000000
130         130    0.022652
101         101    0.019195
80           80    0.018707
25           25    0.018574
..          ...         ...
47           47    0.000000
46           46    0.000000
45           45    0.000000
44           44    0.000000
149         149    0.000000

[150 rows x 2 columns]

In [10]:
Test.loc[Test['Similarity']>0.02,:]

Poem_index  Similarity
0             0    1.000000
130         130    0.022652

In [18]:
df.loc[130,'Poem']

'Arriving with throats like nipped roses, like a tiny bloom fastened to each neck, nothing else cuts the air quite like this thrum to make the small dog at my feet whine and yelp. So we wait—no excitement pinned to the sky so needled and our days open full of rain for weeks. Nothing yet'

In [21]:
Sim_List = []
for i in range(len(Cos_Sim)):
    for n,j in enumerate(Cos_Sim[i]):
        if (j >= 0.15) and (j< 0.99):
            Sim_List.append([i,n])

Sim_List

[[28, 79], [59, 61], [61, 59], [79, 28]]

In [24]:
def Print_Sims(Ind1,Ind2):
    print(f"1 - {df.loc[Ind1,'Poem']} \n2 - {df.loc[Ind2,'Poem']}\n********")

In [25]:
for Poems in Sim_List:
    Print_Sims(Poems[0],Poems[1])

1 -  I saw thee on thy bridal day—When a burning blush came o’er thee,Though happiness around thee lay,The world all love before thee: 
2 - How do I love thee? Let me count the ways. I love thee to the depth and breadth and height My soul can reach, when feeling out of sight For the ends of being and ideal grace. I love thee to the level of every day's Most quiet need, by sun and candle-light. I love thee
********
1 - Come to me in the silence of the night; Come in the speaking silence of a dream; Come with soft rounded cheeks and eyes as bright As sunlight on a stream;Come back in tears, O memory, hope, love of 
2 - Come when the nights are bright with starsOr when the moon is mellow; Come when the sun his golden barsDrops on the hay-field yellow. Come in the twilight soft and gray, Come in the night or come in the day, Come, O love, whene'er you may, 
********
1 - Come when the nights are bright with starsOr when the moon is mellow; Come when the sun his golden barsDrops on the hay-f

In [26]:
Cos_Sim[28]

array([0.        , 0.        , 0.00790382, 0.        , 0.        ,
       0.00983396, 0.        , 0.        , 0.00662234, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.00987786,
       0.        , 0.00596875, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.00307366, 0.01054722, 0.        , 1.        , 0.0096579 ,
       0.        , 0.00857209, 0.04625298, 0.        , 0.        ,
       0.00628446, 0.        , 0.01867034, 0.01161551, 0.00789433,
       0.02984163, 0.        , 0.        , 0.        , 0.00282757,
       0.0074316 , 0.00659283, 0.00307606, 0.        , 0.03887111,
       0.00645685, 0.00871927, 0.        , 0.0032582 , 0.01449641,
       0.006229  , 0.01359981, 0.        , 0.00287314, 0.00339465,
       0.05482812, 0.01865386, 0.00297947, 0.        , 0.02021154,
       0.00293738, 0.01339542, 0.        , 0.        , 0.00606638,
       0.04699716, 0.        , 0.00262162, 0.        , 0.01848

In [27]:
Test = pd.DataFrame(list(enumerate(Cos_Sim[28])), columns = ['Poem_index','Similarity'])

In [30]:
Test.sort_values(by="Similarity",ascending=False)

Poem_index  Similarity
28           28    1.000000
79           79    0.208207
102         102    0.060568
60           60    0.054828
70           70    0.046997
..          ...         ...
57           57    0.000000
52           52    0.000000
48           48    0.000000
43           43    0.000000
149         149    0.000000

[150 rows x 2 columns]